
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: audio-processor
spec:
  template:
    spec:
      containers:
        - image: stephyng/knative-audio-processing-monolithic:latest
          ports:
            - containerPort: 8080
          env:
            - name: MINIO_ENDPOINT
              value: "minio.minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"